# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
# https://docs.coderabbit.ai/guides/configure-coderabbit/

language: "en-US"
early_access: true
reviews:
  profile: "chill"
  high_level_summary: true
  request_changes_workflow: false
  review_status: false
  collapse_walkthrough: false
  poem: false
  auto_review:
    enabled: true
    auto_incremental_review: false
    drafts: false
    base_branches:
      - master
      - beta
      - rc
  path_instructions:
    - path: "**/*"
      instructions: "
      Focus on code smells, logic errors, edge cases, missing test cases, security flaws and serious issues.
      Avoid commenting on minor issues such as linting, formatting and style issues.
      This project uses tabs instead of spaces, do not suggest usage of spaces over tabs.
      Are there any 'red flags' in this code that might warrant closer investigation from a security standpoint?
      Explain what makes them suspicious.
      "
    - path: "**/*.py"
      instructions: "
      _, pgettext, ngettext, and ngettext are defined globally, errors for this being undefined can be ignored.
      "
    - path: "**/*.md"
      instructions: "
      Focus on grammar, spelling, and punctuation.
      Also consider readability and clarity of contents.
      Ensure that changes follow the style of one sentence per line, suggest changes if this is not met.
      "
  tools:
    github-checks:
      enabled: true
    ruff:
      enabled: true
    markdownlint:
      # We use custom markdown syntax such as {#Anchor} for anchors.
      # This is not supported by markdownlint.
      # In future we plan to introduce markdownlint directly with custom rules. (#16453)
      enabled: false
chat:
  auto_reply: true
