repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    # Checks python syntax
    - id: check-ast
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: end-of-file-fixer
    - id: trailing-whitespace

- repo: https://github.com/asottile/add-trailing-comma
  rev: v3.1.0
  hooks:
  # Ruff preserves indent/new-line formatting of function arguments, list items, and similar iterables,
  # if a trailing comma is added.
  # This adds a trailing comma to args/iterable items in case it was missed.
  - id: add-trailing-comma

- repo: https://github.com/astral-sh/ruff-pre-commit
  # Matches Ruff version in requirements.
  rev: v0.5.0
  hooks:
    - id: ruff
      name: lint with ruff
      args: [ --fix --output-file=.\testOutput\lint\PR-lint.xml --output-format=junit ]
    - id: ruff-format
      name: format with ruff

- repo: local
  hooks:
    - id: checkPot
      name: translation string check
      entry: cmd.exe /c "scons checkPot"
      language: system
      pass_filenames: false
      types: [python, pofile]
    - id: unitTest
      name: unit tests
      entry: ./rununittests.bat --output-file ".\testOutput\unit\unitTests.xml" -v
      language: script
      pass_filenames: false
      types: [python, c, c++, batch]
    - id: licenseCheck
      name: Check license compatibility of pip dependencies
      files: requirements.txt
      entry: ./runlicensecheck.bat .\testOutput\license\
      language: script
      pass_filenames: false
