# Configuration file for `prek`, a git hook framework written in Rust.
# See https://prek.j178.dev for more information.
#:schema https://www.schemastore.org/prek.json

exclude = '^user_docs/(?!en/).+/.+\.md$'
default_language_version = { python = "python3.13" }

[[repos]]
repo = "meta"
hooks = [
  { id = "check-useless-excludes" },
  { id = "check-hooks-apply" }
]

[[repos]]
repo = "https://github.com/pre-commit/pre-commit-hooks"
rev = "v6.0.0"
hooks = [
  {
    id = "no-commit-to-branch",
    args = [
      "--branch",
      "master",
      "--branch",
      "beta",
      "--branch",
      "rc"
    ]
  },
  {
    id = "check-added-large-files",
    exclude_types = [
      "pofile",
      "ttf"
    ],
    exclude = '\.(dic|sfd|xliff)$'
  },
  { id = "check-ast" },
  { id = "check-case-conflict" },
  { id = "check-merge-conflict" },
  { id = "debug-statements" },
  {
    id = "trailing-whitespace",
    groups = ["autofix"],
    types_or = [
      "python",
      "c",
      "c++",
      "batch",
      "markdown",
      "toml",
      "yaml",
      "powershell"
    ]
  },
  {
    id = "end-of-file-fixer",
    groups = ["autofix"],
    types_or = [
      "python",
      "c",
      "c++",
      "batch",
      "markdown",
      "toml",
      "yaml",
      "powershell"
    ]
  },
  {
    id = "fix-byte-order-marker",
    groups = ["autofix"],
    types_or = [
      "python",
      "c",
      "c++",
      "batch",
      "markdown",
      "toml",
      "yaml",
      "powershell"
    ]
  },
  { id = "check-toml" },
  { id = "check-yaml" },
  { id = "check-xml" },
  { id = "check-vcs-permalinks" },
  { id = "check-illegal-windows-names" },
  {
    id = "name-tests-test",
    args = ["--unittest"],
    exclude = """
(?x)^tests/(
  checkPot.py |  # Doesn't use unittest
  system |  # Uses robot
  unit/ (
    # Test helpers
    textProvider.py |
    extensionPointTestHelpers.py |
    objectProvider.py |
    test_speechManager/speechManagerTestHarness.py
  )
)
"""
  }
]

[[repos]]
repo = "https://github.com/rhysd/actionlint"
rev = "v1.7.12"
hooks = [
  { id = "actionlint" }
]

[[repos]]
repo = "https://github.com/asottile/add-trailing-comma"
rev = "v4.0.0"
hooks = [
  { id = "add-trailing-comma", groups = ["autofix"] }
]

[[repos]]
repo = "https://github.com/astral-sh/ruff-pre-commit"
rev = "v0.15.9"
hooks = [
  {
    id = "ruff",
    name = "lint with ruff",
    groups = ["autofix"],
    args = ["--fix"]
  },
  {
    id = "ruff-format",
    name = "format with ruff",
    groups = ["autofix"]
  }
]

[[repos]]
repo = "https://github.com/astral-sh/uv-pre-commit"
rev = "0.11.7"
hooks = [
  {
    id = "uv-lock",
    name = "Verify uv lock file",
    groups = ["autofix"],
    args = ["-p3.13"]
  }
]

[[repos]]
repo = "https://github.com/DavidAnson/markdownlint-cli2"
rev = "v0.22.0"
hooks = [
  {
    id = "markdownlint-cli2",
    name = "Lint markdown files",
    groups = ["autofix"],
    args = ["--fix"]
  }
]

[[repos]]
repo = "local"
hooks = [
  {
    id = "checkPo",
    name = "Check po files",
    entry = "uv run source/l10nUtil.py checkPo",
    language = "python",
    types = ["pofile"]
  },
  {
    id = "scons-source",
    name = "build c/c++ files",
    entry = 'cmd.exe /c "scons source --all-cores"',
    language = "system",
    pass_filenames = false,
    types_or = [
      "c",
      "c++"
    ]
  },
  {
    id = "checkPot",
    name = "translation string check",
    entry = "./runcheckpot.bat --all-cores",
    language = "script",
    pass_filenames = false,
    types = ["python"],
    files = "^source/.*$",
    exclude = "(sconscript|sconstruct)$"
  },
  {
    id = "unitTest",
    name = "unit tests",
    entry = "./rununittests.bat",
    language = "script",
    pass_filenames = false,
    types_or = [
      "python",
      "c",
      "c++",
      "batch"
    ]
  },
  {
    id = "licenseCheck",
    name = "Check license compatibility of pip dependencies",
    files = '^(runlicensecheck\.bat|pyproject\.toml)$',
    entry = "./runlicensecheck.bat",
    language = "script",
    pass_filenames = false
  },
  {
    id = "pyright",
    name = "type check with pyright",
    entry = "uv run pyright",
    language = "system",
    types = ["python"],
    exclude = "(sconscript|sconstruct)$"
  }
]
