# Copyright(C) 2023 NV Access Limited, Leonard de Ruijter
# This file is covered by the GNU Lesser General Public License, version 2.1.
# See the file license.txt for more details.

[package]
name = "nvda"
version = "0.1.0"
edition = "2021"

[build-dependencies]
bindgen = "0.69.1"

[dependencies.windows]
version = "0.52"
features = [
    "Win32_Foundation",
]
