name: "Add-on Integration Request"
description: "Propose an existing community add-on for integration into NVDA's core."
title: "[add-on Integration] <Name of add-on>"
labels: ["enhancement", "add-on/integration"]

body:
  - type: markdown
    attributes:
      value: |
        This template is for integrating *existing* community add-ons.
        Please provide the following information to help us evaluate your request.
        Note: For new feature ideas, please use the "Feature Request" template.

        Please also note that the NVDA project has a [Citizen and Contributor Code of Conduct](https://github.com/nvaccess/nvda/blob/master/CODE_OF_CONDUCT.md).
        NV Access expects that all contributors and other community members read and abide by the rules set out in this document while participating or contributing to this project.
        This includes creating or commenting on issues and pull requests.

  - type: input
    id: add-on-name
    attributes:
      label: "Name of the add-on"
      description: "The official name of the add-on you are proposing for integration."
      placeholder: "e.g. Awesome App Support"
    validations:
      required: true

  - type: input
    id: add-on-link
    attributes:
      label: "Link to add-on repository or website"
      description: "Where can we find the source code for this add-on?"
      placeholder: "https://github.com/user/add-on-repo"
    validations:
      required: true

  - type: input
    id: add-on-maintainers
    attributes:
      label: "Current maintainer(s)"
      description: "Please provide the GitHub username(s) or name(s) of the current maintainer(s)."
      placeholder: "@username or 'Name'"
    validations:
      required: false

  - type: textarea
    id: user-impact
    attributes:
      label: "User impact and utility"
      description: |
        This section helps us understand the benefit for users.

        * What problem does this add-on solve for NVDA users?
        * Who is the target audience for this add-on (e.g. all users, developers, users of a specific application)?
        * How widely used is this add-on? Please provide any available data or anecdotal evidence of its popularity (e.g. download numbers, community feedback).
      placeholder: "Describe the problem solved, target users and estimated usage."
    validations:
      required: true

  - type: dropdown
    id: license
    attributes:
      label: "Add-on License Status"
      description: "NVDA is licensed under GPL-2.0 or later. To be included, the add-on's code must be available under these terms. Please specify the add-on's current license situation."
      options:
        - "GPL-2.0 or later (No relicensing needed)"
        - "Other GPL-compatible license (Author has agreed to relicense)"
        - "Other GPL-compatible license (Relicensing permission is not yet confirmed)"
        - "I don't know / Needs investigation"
    validations:
      required: true

  - type: dropdown
    id: maintenance
    attributes:
      label: "Maintenance and future development"
      description: "Are the current maintainers willing and able to continue supporting the add-on after integration?"
      options:
        - "Yes"
        - "No"
        - "I don't know"
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Why should this be in NVDA vs. remaining an add-on?"
      description: |
        - Why is it beneficial for this functionality to be built into NVDA directly?
        - Are there other add-ons that provide similar functionality? If so, why is this one the preferred solution for integration?
      placeholder: "Justify the need for NVDA integration."
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context"
      description: "Please provide any other information that you believe is relevant to this integration request."
      placeholder: "Dependencies, potential conflicts or other relevant details."
