name: Custom issue
description: Is your issue not covered by our bug report or feature request template?

body:
  - type: markdown
    attributes:
      value: |
        It is expected that almost every issue on this project is either a feature request or bug report.
        Please only select this format in exceptional circumstances, otherwise it will be closed.
        Alternatively, consider a [GitHub discussion](https://github.com/nvaccess/nvda/discussions).
        Please read [our guide](https://github.com/nvaccess/nvda/blob/master/devDocs/githubIssueTemplateExplanationAndExamples.md) on how to fill in this template, including how to provide the required files.
        Issues may be closed if the required information is not present.
        Please also note that the NVDA project has a [Citizen and Contributor Code of Conduct](https://github.com/nvaccess/nvda/blob/master/CODE_OF_CONDUCT.md).
        NV Access expects that all contributors and other community members read and abide by the rules set out in this document while participating or contributing to this project.
        This includes creating or commenting on issues and pull requests. 

  - type: textarea
    id: info
    attributes:
      label: Issue information
