import manager

getVirtualBuffer=manager.getVirtualBuffer
insertVirtualBuffer=manager.insertVirtualBuffer
removeVirtualBuffer=manager.removeVirtualBuffer
updateVirtualBuffers=manager.updateVirtualBuffers
registerVirtualBufferClass=manager.registerVirtualBufferClass
unregisterVirtualBufferClass=manager.unregisterVirtualBufferClass
