import vision
import driverHandler
import wx
from autoSettingsUtils.utils import StringParameterInfo
from vision.providerBase import VisionEnhancementProviderSettings, SupportedSettingType
from typing import Optional, Type, Any, List


class AutoGuiTestSettings(VisionEnhancementProviderSettings):

	#: dictionary of the setting id's available when provider is running.
	_availableRuntimeSettings = [
	]

	shouldDoX: bool
	shouldDoY: bool
	amountOfZ: int
	nameOfSomething: str

	availableNameofsomethings = {
		"n1": StringParameterInfo(id="n1", displayName="name one"),
		"n2": StringParameterInfo(id="n2", displayName="name two"),
		"n3": StringParameterInfo(id="n3", displayName="name three"),
		"n4": StringParameterInfo(id="n4", displayName="name four"),
	}

	runtimeOnlySetting: int

	@classmethod
	def getId(cls) -> str:
		return "autoGui"

	@classmethod
	def getTranslatedName(cls) -> str:
		return "Auto Gui"  # Should actually be translated with _() method.

	@classmethod
	def _get_preInitSettings(cls) -> SupportedSettingType:
		return [
			driverHandler.BooleanDriverSetting(
				"shouldDoX",  # value stored in matching property name on class
				"Should Do X",
				defaultVal=True
			),
			driverHandler.BooleanDriverSetting(
				"shouldDoY",  # value stored in matching property name on class
				"Should Do Y",
				defaultVal=False
			),
			driverHandler.NumericDriverSetting(
				"amountOfZ",  # value stored in matching property name on class
				"Amount of Z",
				defaultVal=11
			),
			driverHandler.DriverSetting(
				# options for this come from a property with name generated by
				# f"available{settingID.capitalize()}s"
				# Note:
				#   First letter of Id becomes capital, the rest lowercase.
				#   the 's' character on the end.
				# result: 'availableNameofsomethings'
				"nameOfSomething",  # value stored in matching property name on class
				"Name of something",
			)
		]

	def clearRuntimeSettings(self):
		self._availableRuntimeSettings = []

	def addRuntimeSettingsAvailibility(self, settingIDs: List[str]):
		self._availableRuntimeSettings.extend(settingIDs)
		# ensure any previously saved settings are loaded from config file:
		self._initSpecificSettings(self, self._getAvailableRuntimeSettings())

	def _hasFeature(self, settingID: str) -> bool:
		return settingID in self._availableRuntimeSettings

	def _getAvailableRuntimeSettings(self) -> SupportedSettingType:
		settings = []
		if self._hasFeature("runtimeOnlySetting"):
			settings.extend([
				driverHandler.NumericDriverSetting(
					"runtimeOnlySetting",  # value stored in matching property name on class
					"Runtime Only amount",
					defaultVal=50,
				),
			])
		return settings

	def _get_supportedSettings(self) -> SupportedSettingType:
		settings = []
		settings.extend(self.preInitSettings)
		settings.extend(self._getAvailableRuntimeSettings())
		return settings


class AutoGuiTestProvider(vision.providerBase.VisionEnhancementProvider):
	_settings = AutoGuiTestSettings()

	@classmethod
	def canStart(cls):
		return True  # Check any dependencies (Windows version, Hardware access, Installed applications)

	@classmethod
	def getSettingsPanelClass(cls) -> Optional[Type]:
		"""Returns the instance to be used in order to construct a settings panel for the provider.
		@return: Optional[SettingsPanel]
		@remarks: When None is returned, L{gui.settingsDialogs.VisionProviderSubPanel_Wrapper} is used.
		"""
		return None  # No custom GUI

	@classmethod
	def getSettings(cls) -> AutoGuiTestSettings:
		return cls._settings

	def __init__(self):
		super().__init__()
		self._initRuntimeOnlySettings()
		self._showCurrentConfig()

	def _initRuntimeOnlySettings(self):
		""" This method might query another application for its capabilities and initialise these configuration
			options.
		"""
		settings = self.getSettings()
		settings.addRuntimeSettingsAvailibility(["runtimeOnlySetting"])
		if not hasattr(settings, "runtimeOnlySetting"):
			#  Set the default
			settings.runtimeOnlySetting = self._getValueFromDeviceOrOtherApplication("runtimeOnlySetting")

	def _getValueFromDeviceOrOtherApplication(self, settingId: str) -> Any:
		""" This method might connect to another application / device and fetch default values."""
		return 75

	def _showCurrentConfig(self):
		"""Simple mechanism to test updating values."""
		result = (
			f"AutoGuiTestProvider:\n"
			f"x: {self._settings.shouldDoX}\n"
			f"y: {self._settings.shouldDoY}\n"
			f"z: {self._settings.amountOfZ}\n"
			f"name: {self._settings.nameOfSomething}\n"
			f"runtimeOnlySetting: {self._settings.runtimeOnlySetting}"
		)
		wx.MessageBox(result, caption="started")

	def terminate(self):
		self._settings.clearRuntimeSettings()
		super().terminate()

	def registerEventExtensionPoints(self, extensionPoints):
		pass


VisionEnhancementProvider = AutoGuiTestProvider
