--loglevel DEBUG
--outputdir testOutput\system
--xunit systemTests.xml
--pythonpath .\tests\system\libraries
--exclude excluded_from_build
--include fakeTagToEnforceUsageOfInclude
--variable whichNVDA:source
--variable installDir:
