# A part of NonVisual Desktop Access (NVDA)
# This file is covered by the GNU General Public License.
# See the file COPYING for more details.
# Copyright (C) 2006-2020 NV Access Limited, Peter Vágner, Aleksey Sadovoy, Babbage B.V., Bill Dengler,
# Julien Cochuyt

from .speech import (
	_extendSpeechSequence_addMathForTextInfo,
	_getSpellingSpeechAddCharMode,
	_getSpellingCharAddCapNotification,
	_getSpellingSpeechWithoutCharMode,
	_getPlaceholderSpeechIfTextEmpty,
	_getSelectionMessageSpeech,
	_getSpeakMessageSpeech,
	_manager,
	_objectSpeech_calculateAllowedProps,
	_suppressSpeakTypedCharacters,
	_suppressSpeakTypedCharactersNumber,
	_suppressSpeakTypedCharactersTime,
	beenCanceled,
	BLANK_CHUNK_CHARS,
	cancelSpeech,
	CHUNK_SEPARATOR,
	clearTypedWordBuffer,
	curWordChars,
	FIRST_NONCONTROL_CHAR,
	getCharDescListFromText,
	getControlFieldSpeech,
	getCurrentLanguage,
	getFormatFieldSpeech,
	getIndentationSpeech,
	getObjectPropertiesSpeech,
	getObjectSpeech,
	getPreselectedTextSpeech,
	getPropertiesSpeech,
	getSpellingSpeech,
	getTableInfoSpeech,
	getTextInfoSpeech,
	IDT_BASE_FREQUENCY,
	IDT_MAX_SPACES,
	IDT_TONE_DURATION,
	isBlank,
	isPaused,
	LANGS_WITH_CONJUNCT_CHARS,
	oldColumnNumber,
	oldColumnSpan,
	oldRowNumber,
	oldRowSpan,
	oldTableID,
	oldTreeLevel,
	pauseSpeech,
	processText,
	PROTECTED_CHAR,
	RE_CONVERT_WHITESPACE,
	RE_INDENTATION_CONVERT,
	RE_INDENTATION_SPLIT,
	speak,
	speakMessage,
	speakObject,
	speakObjectProperties,
	speakPreselectedText,
	speakSelectionChange,
	speakSelectionMessage,
	speakSpelling,
	speakText,
	speakTextInfo,
	speakTextSelected,
	speakTypedCharacters,
	speechMode,
	speechMode_beeps,
	speechMode_beeps_ms,
	speechMode_off,
	speechMode_talk,
	spellTextInfo,
	splitTextIndentation,
)

from .priorities import Spri

from .types import (
	SpeechSequence,
	SequenceItemT,
	logBadSequenceTypes,
	GeneratorWithReturn,
	_flattenNestedSequences
)

__all__ = [
	# from .priorities
	"Spri",
	# from .types
	"SpeechSequence",
	"SequenceItemT",
	"logBadSequenceTypes",
	"GeneratorWithReturn",
	"_flattenNestedSequences",
	# from .speech
	"_getSpellingSpeechAddCharMode",
	"_getSpellingCharAddCapNotification",
	"_getSpellingSpeechWithoutCharMode",
	"_extendSpeechSequence_addMathForTextInfo",
	"_getPlaceholderSpeechIfTextEmpty",
	"_getSelectionMessageSpeech",
	"_getSpeakMessageSpeech",
	"_manager",
	"_objectSpeech_calculateAllowedProps",
	"_suppressSpeakTypedCharacters",
	"_suppressSpeakTypedCharactersNumber",
	"_suppressSpeakTypedCharactersTime",
	"beenCanceled",
	"BLANK_CHUNK_CHARS",
	"cancelSpeech",
	"CHUNK_SEPARATOR",
	"clearTypedWordBuffer",
	"curWordChars",
	"FIRST_NONCONTROL_CHAR",
	"getCharDescListFromText",
	"getControlFieldSpeech",
	"getCurrentLanguage",
	"getFormatFieldSpeech",
	"getIndentationSpeech",
	"getObjectPropertiesSpeech",
	"getObjectSpeech",
	"getPreselectedTextSpeech",
	"getPropertiesSpeech",
	"getSpellingSpeech",
	"getTableInfoSpeech",
	"getTextInfoSpeech",
	"IDT_BASE_FREQUENCY",
	"IDT_MAX_SPACES",
	"IDT_TONE_DURATION",
	"isBlank",
	"isPaused",
	"LANGS_WITH_CONJUNCT_CHARS",
	"oldColumnNumber",
	"oldColumnSpan",
	"oldRowNumber",
	"oldRowSpan",
	"oldTableID",
	"oldTreeLevel",
	"pauseSpeech",
	"processText",
	"PROTECTED_CHAR",
	"RE_CONVERT_WHITESPACE",
	"RE_INDENTATION_CONVERT",
	"RE_INDENTATION_SPLIT",
	"speak",
	"speakMessage",
	"speakObject",
	"speakObjectProperties",
	"speakPreselectedText",
	"speakSelectionChange",
	"speakSelectionMessage",
	"speakSpelling",
	"speakText",
	"speakTextInfo",
	"speakTextSelected",
	"speakTypedCharacters",
	"speechMode",
	"speechMode_beeps",
	"speechMode_beeps_ms",
	"speechMode_off",
	"speechMode_talk",
	"spellTextInfo",
	"splitTextIndentation",
]

import synthDriverHandler
import config


def initialize():
	"""Loads and sets the synth driver configured in nvda.ini."""
	synthDriverHandler.initialize()
	synthDriverHandler.setSynth(config.conf["speech"]["synth"])


def terminate():
	synthDriverHandler.setSynth(None)
