//NVDAController_appModuleHelper.idl

/**
 * Allows the controling of NVDA from a remote process
 */
[
	uuid(ec0ac5e3-de3f-49dc-b9d8-571abd7ddd92),
	version(1.0),
]
interface NvdaController {

/**
 * Retreaves the version of NVDA.
 * @param version  a pointer to the version string, must be freed when finnished with
 */
	error_status_t getNVDAVersionString([out,string] wchar_t** version);

/**
 * Instructs NVDA to speak the given text.
 * @param text the text to speak.
 */
	error_status_t speakText([in,string] const wchar_t* text);

/**
 * Instructs NVDA to silence current speech.
 */
	error_status_t cancelSpeech();

/**
 * Shows a given message on the braille display.
 * @param message the message that will be temporarily shown on the display
 */
	error_status_t brailleMessage([in,string] const wchar_t* message);

/**
 * Tests if NVDA is running or not.
 */
	error_status_t testIfRunning();

};
