//NVDAController_appModuleHelper.idl

/**
 * Allows the controling of NVDA from a remote process
 */
[
	uuid(ec0ac5e3-de3f-49dc-b9d8-571abd7ddd92),
	version(1.0),
]
interface NvdaController {

/**
 * Retreaves the version of NVDA.
 * @param version  a pointer to the version string, must be freed when finnished with
 */
	error_status_t __stdcall getNVDAVersionString([out,string] wchar_t** version);

/**
 * Instructs NVDA to speak the given text.
 * @param text the text to speak.
 */
	error_status_t __stdcall speakText([in,string] const wchar_t* text);

/**
 * Instructs NVDA to silence current speech.
 */
	error_status_t __stdcall cancelSpeech();

/**
 * Shows a given message on the braille display.
 * @param message the message that will be temporarily shown on the display
 */
	error_status_t __stdcall brailleMessage([in,string] const wchar_t* message);

/**
 * Tests if NVDA is running or not.
 */
	error_status_t __stdcall testIfRunning();

/**
 * Notifies NVDA that the keyboard layout / input locale for this thread has changed.
 * @param threadID the thread the layout change occured in
 * @param hkl the current layout retreaved either by GetKeyboardLayout or the lParam of wm_inputLangChange.
 * @param layoutString the current identifier string returned from GetKeyboardLayoutName.
 */
	error_status_t __stdcall inputLangChangeNotify([in] long threadID, [in] long hkl, [in,string] wchar_t* layoutString);

};
