
ROLE_UNKNOWN=0
ROLE_WINDOW=1
ROLE_TITLEBAR=2
ROLE_PANEL=3
ROLE_DIALOG=4
ROLE_CHECKBOX=5
ROLE_RADIOBUTTON=6
ROLE_STATICTEXT=7
ROLE_EDITABLETEXT=8
ROLE_BUTTON=9
ROLE_MENUBAR=10
ROLE_MENUITEM=11
ROLE_POPUPMENU=12
ROLE_COMBOBOX=13
ROLE_LIST=14
ROLE_LISTITEM=15
ROLE_GRAPHIC=16
ROLE_HELPBALLOON=17
ROLE_TOOLTIP=18
ROLE_LINK=19
ROLE_TREEVIEW=20
ROLE_TREEVIEWITEM=21
ROLE_TAB=22
ROLE_TABCONTROL=23
ROLE_SLIDER=24
ROLE_PROGRESSBAR=25
ROLE_SCROLLBAR=26
ROLE_STATUSBAR=27
ROLE_TABLE=28
ROLE_TABLECELL=29
ROLE_TABLECOLUMN=30
ROLE_TABLEROW=31
ROLE_TABLECOLUMNHEADER=32
ROLE_TABLEROWHEADER=33
ROLE_FRAME=34
ROLE_TOOLBAR=35
ROLE_DROPDOWNBUTTON=36
ROLE_CLOCK=37

STATE_UNAVAILABLE=1
STATE_SELECTED=2
STATE_BUSY=4
STATE_PRESSED=8
STATE_CHECKED=16
STATE_HALFCHECKED=32
STATE_READONLY=64
STATE_EXPANDED=128
STATE_INVISIBLE=256
STATE_VISITED=512
STATE_LINKED=1024
STATE_HASPOPUP=2048
STATE_PROTECTED=8192
STATE_REQUIRED=16384

speechRoleLabels={
	ROLE_UNKNOWN:_("unknown object"),
	ROLE_WINDOW:_("window"),
	ROLE_TITLEBAR:_("title bar"),
	ROLE_PANEL:_("panel"),
	ROLE_DIALOG:_("dialog"),
	ROLE_CHECKBOX:_("check box"),
	ROLE_RADIOBUTTON:_("radio button"),
	ROLE_STATICTEXT:_("text"),
	ROLE_EDITABLETEXT:_("edit"),
	ROLE_BUTTON:_("button"),
	ROLE_MENUBAR:_("menu bar"),
	ROLE_MENUITEM:_("menu item"),
	ROLE_POPUPMENU:_("popup menu"),
	ROLE_COMBOBOX:_("combo box"),
	ROLE_LIST:_("list"),
	ROLE_LISTITEM:_("list item"),
	ROLE_GRAPHIC:_("graphic"),
	ROLE_HELPBALLOON:_("help balloon"),
	ROLE_TOOLTIP:_("tool tip"),
	ROLE_LINK:_("link"),
	ROLE_TREEVIEW:_("tree view"),
	ROLE_TREEVIEWITEM:_("tree view item"),
	ROLE_TAB:_("tab"),
	ROLE_TABCONTROL:_("tab control"),
	ROLE_SLIDER:_("slider"),
	ROLE_PROGRESSBAR:_("progress bar"),
	ROLE_SCROLLBAR:_("scroll bar"),
	ROLE_STATUSBAR:_("status bar"),
	ROLE_TABLE:_("table"),
	ROLE_TABLECELL:_("cell"),
	ROLE_TABLECOLUMN:_("column"),
	ROLE_TABLEROW:_("row"),
	ROLE_FRAME:_("frame"),
	ROLE_TOOLBAR:_("tool bar"),
	ROLE_TABLECOLUMNHEADER:_("column header"),
	ROLE_TABLEROWHEADER:_("row header"),
	ROLE_DROPDOWNBUTTON:_("drop down button"),
	ROLE_CLOCK:_("clock"),
}

speechStateLabels={
	STATE_UNAVAILABLE:_("unavailable"),
	STATE_SELECTED:_("selected"),
	STATE_BUSY:_("busy"),
	STATE_PRESSED:_("pressed"),
	STATE_CHECKED:_("checked"),
	STATE_HALFCHECKED:_("half checked"),
	STATE_READONLY:_("read only"),
	STATE_EXPANDED:_("expanded"),
	STATE_INVISIBLE:_("invisible"),
	STATE_VISITED:_("visited"),
	STATE_LINKED:_("linked"),
	STATE_HASPOPUP:_("subMenu"),
	STATE_PROTECTED:_("protected"),
	STATE_REQUIRED:_("required"),
}
