#IAccessibleHandler.py
#A part of NonVisual Desktop Access (NVDA)
#Copyright (C) 2006-2007 Michael Curran <mick@kulgan.net>
#This file is covered by the GNU General Public License.
#See the file COPYING for more details.

import comtypesClient
import ctypes

IServiceProvider=comtypesClient.GetModule('lib/ServProv.tlb').IServiceProvider
IA2Lib=comtypesClient.GetModule('lib/ia2.tlb')

(EVENT_ACTION_CHANGED,
EVENT_ACTIVE_DECENDENT_CHANGED,
EVENT_DOCUMENT_ATTRIBUTE_CHANGED,
EVENT_DOCUMENT_CONTENT_CHANGED,
EVENT_DOCUMENT_LOAD_COMPLETE,
EVENT_DOCUMENT_LOAD_STOPPED,
EVENT_DOCUMENT_RELOAD,
EVENT_HYPERLINK_END_INDEX_CHANGED,
EVENT_HYPERLINK_NUMBER_OF_ANCHORS_CHANGED,
EVENT_HYPERLINK_SELECTED_LINK_CHANGED,
EVENT_HYPERTEXT_LINK_ACTIVATED,
EVENT_HYPERTEXT_LINK_SELECTED,
EVENT_HYPERLINK_START_INDEX_CHANGED,
EVENT_HYPERTEXT_CHANGED,
EVENT_HYPERTEXT_NLINKS_CHANGED,
EVENT_OBJECT_ATTRIBUTE_CHANGED,
EVENT_PAGE_CHANGED,  
EVENT_ROLE_CHANGED,
EVENT_TABLE_CAPTION_CHANGED,
EVENT_TABLE_COLUMN_DESCRIPTION_CHANGED,
EVENT_TABLE_COLUMN_HEADER_CHANGED,
EVENT_TABLE_MODEL_CHANGED,
EVENT_TABLE_ROW_DESCRIPTION_CHANGED,
EVENT_TABLE_ROW_HEADER_CHANGED,
EVENT_TABLE_SUMMARY_CHANGED,
EVENT_TEXT_ATTRIBUTE_CHANGED,
EVENT_TEXT_CARET_MOVED,
EVENT_TEXT_CHANGED,
EVENT_TEXT_INSERTED,
EVENT_TEXT_REMOVED,
EVENT_TEXT_UPDATED,
EVENT_TEXT_SELECTION_CHANGED,
EVENT_VISIBLE_DATA_CHANGED,
EVENT_COLUMN_CHANGED,
EVENT_SECTION_CHANGED,
)=range(0x101,0x101+35)

def IA2FromMSAA(pacc):
	try:
		s=pacc.QueryInterface(IServiceProvider)
		i=s.QueryService(ctypes.byref(IA2Lib.IAccessible2._iid_),ctypes.byref(IA2Lib.IAccessible2._iid_))
		newPacc=ctypes.POINTER(IA2Lib.IAccessible2)(i)
		return newPacc
	except:
		return None
