#keyLabels.py
#A part of NonVisual Desktop Access (NVDA)
#This file is covered by the GNU General Public License.
#See the file COPYING for more details.
#Copyright (C) 2008-2010 James Teh <jamie@jantrid.net>, Aleksey Sadovoy <lex@onm.su>

localizedKeyLabels = {
	'browserBack': _("back"),
	'browserForward': _("forward"),
	'browserRefresh': _("refresh"),
	'browserStop': _("browser stop"),
	'browserSearch': _("search page"),
	'browserFavorites': _("favorites"),
	'browserHome': _("home page"),
	'volumeMute': _("mute"),
	'volumeDown': _("volume down"),
	'volumeUp': _("volume up"),
	'mediaNextTrack': _("next track"),
	'mediaPrevTrack': _("previous track"),
	'mediaStop': _("stop"),
	'mediaPlayPause': _("play pause"),
	'launchMail': _("email"),
	'launchMediaPlayer': _("media player"),
	'launchApp1': _("custom application 1"),
	'launchApp2': _("custom application 2"),
	'backspace': _("backspace"),
	'capsLock': _("caps lock"),
	'control': _("ctrl"),
	'alt': _("alt"),
	'shift': _("shift"),
	'windows': _("windows"),
	'enter': _("enter"),
	'numpadEnter': _("numpad enter"),
	'escape': _("escape"),
	'space': _("space"),
	'pageUp': _("page up"),
	'pageDown': _("page down"),
	'end': _("end"),
	'home': _("home"),
	'delete': _("delete"),
	'numpadDelete': _("numpad delete"),
	'leftArrow': _("left arrow"),
	'rightArrow': _("right arrow"),
	'upArrow': _("up arrow"),
	'downArrow': _("down arrow"),
	'applications': _("applications"),
	'numLock': _("num lock"),
	'printScreen': _("print screen"),
	'scrollLock': _("scroll lock"),
	'numpad4': _("numpad 4"),
	'numpad6': _("numpad 6"),
	'numpad8': _("numpad 8"),
	'numpad2': _("numpad 2"),
	'numpad9': _("numpad 9"),
	'numpad3': _("numpad 3"),
	'numpad1': _("numpad 1"),
	'numpad7': _("numpad 7"),
	'numpad5': _("numpad 5"),
	'numpadDivide': _("numpad divide"),
	'numpadMultiply': _("numpad multiply"),
	'numpadMinus': _("numpad minus"),
	'numpadPlus': _("numpad plus"),
	'leftControl': _("left control"),
	'rightControl': _("right control"),
	'leftWindows': _("left windows"),
	'leftShift': _("left shift"),
	'rightShift': _("right shift"),
	'leftAlt': _("left alt"),
	'rightAlt': _("right alt"),
	'rightWindows': _("right windows"),
	'break': _("break"),
}
