# A part of NonVisual Desktop Access (NVDA)
# Copyright (C) 2026 NV Access Limited, Leonard de Ruijter
# This file is covered by the GNU General Public License.
# See the file COPYING for more details.

"""Unit tests for the brailleTableUtil module."""

import ast
import importlib.util
import json
import os
import tempfile
import unittest

import brailleTables
import brailleTableUtil
import globalVars


class TestGenerateTablesSource(unittest.TestCase):
	def test_tableWithLangsAndTableWithFlag(self):
		overrides = {
			"ba.utb": {"input": False},
			"afr-za-g1.ctb": {
				"inputForLangs": ["af_ZA"],
				"outputForLangs": ["af_ZA"],
			},
		}
		louisMetadata = {
			"afr-za-g1.ctb": {"displayName": "Afrikaans grade 1"},
			"ba.utb": {"displayName": "Bashkir grade 1"},
			"notOptedIn.ctb": {"displayName": "Not opted in"},
		}
		source = brailleTableUtil.generateTablesSource(overrides, louisMetadata)
		expected = (
			"# A part of NonVisual Desktop Access (NVDA)\n"
			"# Copyright (C) 2026 NV Access Limited, Leonard de Ruijter\n"
			"# This file is covered by the GNU General Public License.\n"
			"# See the file COPYING for more details.\n"
			"\n"
			"# This file is generated by brailleTableUtil. Do not edit it manually.\n"
			"\n"
			"from . import addTable\n"
			"\n"
			"addTable(\n"
			'\t"afr-za-g1.ctb",\n'
			"\t# Translators: The name of a braille table displayed in the\n"
			"\t# braille settings dialog.\n"
			'\t_("Afrikaans grade 1"),\n'
			'\tinputForLangs={"af_ZA"},\n'
			'\toutputForLangs={"af_ZA"},\n'
			")\n"
			"addTable(\n"
			'\t"ba.utb",\n'
			"\t# Translators: The name of a braille table displayed in the\n"
			"\t# braille settings dialog.\n"
			'\t_("Bashkir grade 1"),\n'
			"\tinput=False,\n"
			")\n"
		)
		self.assertEqual(source, expected)
		ast.parse(source)

	def test_pinnedNameAndFlags(self):
		overrides = {
			"zhcn-g1.ctb": {
				"displayName": "Chinese (China, Mandarin) Current Braille System",
				"contracted": True,
				"output": False,
			},
		}
		louisMetadata = {
			"zhcn-g1.ctb": {"displayName": "Chinese common braille (no tones)"},
		}
		source = brailleTableUtil.generateTablesSource(overrides, louisMetadata)
		expected = (
			"addTable(\n"
			'\t"zhcn-g1.ctb",\n'
			"\t# Translators: The name of a braille table displayed in the\n"
			"\t# braille settings dialog.\n"
			'\t_("Chinese (China, Mandarin) Current Braille System"),\n'
			"\tcontracted=True,\n"
			"\toutput=False,\n"
			")\n"
		)
		self.assertTrue(source.endswith(expected))

	def test_missingDisplayNameRaises(self):
		with self.assertRaises(ValueError):
			brailleTableUtil.generateTablesSource({"no-name.ctb": {}}, {"no-name.ctb": {}})

	def test_tableNamesMatchCaseInsensitively(self):
		overrides = {"No-No-g2.ctb": {}}
		louisMetadata = {"no-no-g2.ctb": {"displayName": "Norwegian grade 2", "contracted": True}}
		source = brailleTableUtil.generateTablesSource(overrides, louisMetadata)
		expected = (
			"addTable(\n"
			'\t"No-No-g2.ctb",\n'
			"\t# Translators: The name of a braille table displayed in the\n"
			"\t# braille settings dialog.\n"
			'\t_("Norwegian grade 2"),\n'
			"\tcontracted=True,\n"
			")\n"
		)
		self.assertTrue(source.endswith(expected))


class TestComputeOverrides(unittest.TestCase):
	def test_onlyDivergencesAreEmitted(self):
		registry = {
			"same.ctb": {"displayName": "Same name"},
			"renamed.ctb": {"displayName": "NVDA name"},
			"flags.ctb": {
				"displayName": "Flags",
				"contracted": True,
				"input": False,
				"inputForLangs": ["nl"],
				"outputForLangs": ["nl_BE", "nl"],
			},
			"noupstream.ctb": {"displayName": "Only NVDA"},
			"uncontracted.ctb": {"displayName": "Uncontracted"},
		}
		louisMetadata = {
			"same.ctb": {"displayName": "Same name"},
			"renamed.ctb": {"displayName": "Upstream name"},
			"flags.ctb": {"displayName": "Flags"},
			"uncontracted.ctb": {"displayName": "Uncontracted", "contracted": True},
			"notOptedIn.ctb": {"displayName": "Not opted in"},
		}
		overrides = brailleTableUtil.computeOverrides(registry, louisMetadata)
		self.assertEqual(
			overrides,
			{
				"flags.ctb": {
					"contracted": True,
					"input": False,
					"inputForLangs": ["nl"],
					"outputForLangs": ["nl", "nl_BE"],
				},
				"noupstream.ctb": {"displayName": "Only NVDA"},
				"renamed.ctb": {"displayName": "NVDA name"},
				"same.ctb": {},
				"uncontracted.ctb": {"contracted": False},
			},
		)
		self.assertEqual(list(overrides), sorted(overrides))

	def test_tableNamesMatchCaseInsensitively(self):
		registry = {
			"No-No-g2.ctb": {"displayName": "Norwegian grade 2", "contracted": True},
		}
		louisMetadata = {
			"no-no-g2.ctb": {"displayName": "Norwegian grade 2", "contracted": True},
		}
		overrides = brailleTableUtil.computeOverrides(registry, louisMetadata)
		self.assertEqual(overrides, {"No-No-g2.ctb": {}})


class TestGeneratedTablesEquivalence(unittest.TestCase):
	"""The module generated from tables.json and liblouis metadata must register
	the exact same tables and language mappings as the checked in tables module.
	"""

	def test_generatedRegistryMatchesBuiltIn(self):
		overridesPath = os.path.join(globalVars.appDir, "brailleTables", "tables.json")
		with open(overridesPath, encoding="utf-8") as f:
			overrides = json.load(f)
		louisMetadata = brailleTableUtil.readLiblouisMetadata()
		source = brailleTableUtil.generateTablesSource(overrides, louisMetadata)
		origTables = brailleTables._tables
		origInputForLangs = brailleTables._inputTableForLangs
		origOutputForLangs = brailleTables._outputTableForLangs
		brailleTables._tables = {}
		brailleTables._inputTableForLangs = {}
		brailleTables._outputTableForLangs = {}
		try:
			with tempfile.TemporaryDirectory() as tempDir:
				modulePath = os.path.join(tempDir, "generatedTables.py")
				with open(modulePath, "w", encoding="utf-8") as f:
					f.write(source)
				spec = importlib.util.spec_from_file_location("brailleTables._generatedForTest", modulePath)
				module = importlib.util.module_from_spec(spec)
				spec.loader.exec_module(module)
			generatedTables = brailleTables._tables
			generatedInputForLangs = brailleTables._inputTableForLangs
			generatedOutputForLangs = brailleTables._outputTableForLangs
		finally:
			brailleTables._tables = origTables
			brailleTables._inputTableForLangs = origInputForLangs
			brailleTables._outputTableForLangs = origOutputForLangs
		self.assertEqual(generatedTables, dict(origTables))
		self.assertEqual(generatedInputForLangs, origInputForLangs)
		self.assertEqual(generatedOutputForLangs, origOutputForLangs)


class TestDiffTables(unittest.TestCase):
	def test_reportCategories(self):
		overrides = {
			"pinned-same.ctb": {"displayName": "Now matches"},
			"pinned-contracted.ctb": {"contracted": True},
			"diverged.ctb": {"displayName": "NVDA name"},
			"gone.ctb": {},
			"plain.ctb": {},
		}
		louisMetadata = {
			"pinned-same.ctb": {"displayName": "Now matches"},
			"pinned-contracted.ctb": {"displayName": "Contracted", "contracted": True},
			"diverged.ctb": {"displayName": "Upstream name"},
			"plain.ctb": {"displayName": "Plain"},
			"new.ctb": {"displayName": "New"},
		}
		diff = brailleTableUtil.diffTables(overrides, louisMetadata)
		self.assertEqual(
			diff,
			{
				"notOptedIn": ["new.ctb"],
				"missingUpstream": ["gone.ctb"],
				"unpinCandidates": {
					"pinned-contracted.ctb": ["contracted"],
					"pinned-same.ctb": ["displayName"],
				},
			},
		)

	def test_tableNamesMatchCaseInsensitively(self):
		overrides = {
			"No-No-g2.ctb": {"displayName": "Norwegian grade 2"},
		}
		louisMetadata = {
			"no-no-g2.ctb": {"displayName": "Norwegian grade 2", "contracted": True},
		}
		diff = brailleTableUtil.diffTables(overrides, louisMetadata)
		self.assertEqual(
			diff,
			{
				"notOptedIn": [],
				"missingUpstream": [],
				"unpinCandidates": {"No-No-g2.ctb": ["displayName"]},
			},
		)

	def test_legacyTblExcludedFromNotOptedIn(self):
		overrides = {
			"kmr.tbl": {"displayName": "Northern Kurdish grade 0"},
		}
		louisMetadata = {
			"kmr.tbl": {"displayName": "Northern Kurdish braille"},
			"ar.tbl": {"displayName": "Arabic uncontracted braille"},
			"ar-ar-g1.utb": {"displayName": "Arabic grade 1 braille"},
		}
		diff = brailleTableUtil.diffTables(overrides, louisMetadata)
		self.assertEqual(
			diff,
			{
				"notOptedIn": ["ar-ar-g1.utb"],
				"missingUpstream": [],
				"unpinCandidates": {},
			},
		)
