# A part of NonVisual Desktop Access (NVDA)
# Copyright (C) 2025 NV Access Limited
# This file may be used under the terms of the GNU General Public License, version 2 or later, as modified by the NVDA license.
# For full terms and any additional permissions, see the NVDA license file: https://github.com/nvaccess/nvda/blob/master/copying.txt

"""Functions exported by user32.dll, and supporting data structures and enumerations."""

from ctypes import (
	Structure,
	WINFUNCTYPE,
	Union,
	c_int,
	c_size_t,
	c_uint,
	c_long,
	c_longlong,
	c_void_p,
	sizeof,
	windll,
	POINTER,
)
from ctypes.wintypes import (
	BOOL,
	COLORREF,
	DWORD,
	BYTE,
	HKL,
	HMODULE,
	HRGN,
	LONG,
	LPDWORD,
	LPPOINT,
	PHANDLE,
	PMSG,
	POINT,
	PRECT,
	RECT,
	HANDLE,
	HHOOK,
	HINSTANCE,
	HMENU,
	HICON,
	HBRUSH,
	HDC,
	HWND,
	LPARAM,
	LPWSTR,
	LPCWSTR,
	LPMSG,
	SHORT,
	UINT,
	WCHAR,
	WORD,
	WPARAM,
	ATOM,
)

UINT_PTR = c_size_t
ULONG_PTR = c_size_t


class PAINTSTRUCT(Structure):
	_fields_ = [
		("hdc", HDC),
		("fErase", BOOL),
		("rcPaint", RECT),
		("fRestore", BOOL),
		("fIncUpdate", BOOL),
		("rgbReserved", BYTE * 32),
	]


# LRESULT is defined as LONG_PTR (signed type)
if sizeof(c_long) == sizeof(c_void_p):
	LRESULT = c_long
elif sizeof(c_longlong) == sizeof(c_void_p):
	LRESULT = c_longlong
else:
	raise RuntimeError("Unsupported platform")


HCURSOR = HANDLE

WNDPROC = WINFUNCTYPE(LRESULT, HWND, c_uint, WPARAM, LPARAM)


class WNDCLASSEXW(Structure):
	_fields_ = [
		("cbSize", c_uint),  # noqa: F405
		("style", c_uint),  # noqa: F405
		("lpfnWndProc", WNDPROC),
		("cbClsExtra", c_int),
		("cbWndExtra", c_int),
		("hInstance", HINSTANCE),  # noqa: F405
		("hIcon", HICON),  # noqa: F405
		("HCURSOR", HCURSOR),
		("hbrBackground", HBRUSH),  # noqa: F405
		("lpszMenuName", LPWSTR),  # noqa: F405
		("lpszClassName", LPWSTR),  # noqa: F405
		("hIconSm", HICON),  # noqa: F405
	]


dll = windll.user32

CallNextHookEx = dll.CallNextHookEx
"""
.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-callnexthookex
"""
CallNextHookEx.argtypes = (
	HHOOK,  # hook
	c_int,  # code
	WPARAM,
	LPARAM,
)
CallNextHookEx.restype = LRESULT

GetMessage = dll.GetMessageW
"""
Retrieves a message from the calling thread's message queue, dispatching incoming sent messages until a posted message is available for retrieval.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getmessagew
"""
GetMessage.argtypes = (
	LPMSG,  # lpMsg
	HWND,  # hWnd
	UINT,  # wMsgFilterMin
	UINT,  # wMsgFilterMax
)
GetMessage.restype = BOOL

HOOKPROC = WINFUNCTYPE(LRESULT, c_int, WPARAM, LPARAM)  # noqa: F405

SetWindowsHookEx = dll.SetWindowsHookExW
SetWindowsHookEx.argtypes = (
	c_int,  # idHook
	HOOKPROC,  # lpfn
	HINSTANCE,  # hMod
	DWORD,  # dwThreadId
)
SetWindowsHookEx.restype = HHOOK

DefWindowProc = dll.DefWindowProcW
"""
Calls the default window procedure to provide default processing for any window messages that an application does not process.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-defwindowprocw
"""
DefWindowProc.argtypes = (
	HWND,
	UINT,  # msg
	WPARAM,
	LPARAM,
)
DefWindowProc.restype = LRESULT

HWINEVENTHOOK = HANDLE
"""
Used to declare a window event hook function.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/winauto/hwineventhook
"""

WINEVENTPROC = WINFUNCTYPE(None, HWINEVENTHOOK, DWORD, HWND, LONG, LONG, DWORD, DWORD)
"""
An application-defined callback that the system calls in response to events generated by an accessible object.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nc-winuser-wineventproc
"""

SetWinEventHook = dll.SetWinEventHook
"""
Sets an event hook function for a range of events.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwineventhook
"""
SetWinEventHook.restype = HWINEVENTHOOK
SetWinEventHook.argtypes = (
	DWORD,  # eventMin: Specifies the lowest event value that is handled by the hook function
	DWORD,  # eventMax: Specifies the highest event value that is handled by the hook function
	HMODULE,  # hmodWinEventProc: Handle to the DLL that contains the hook function, if the WINEVENT_INCONTEXT flag is specified, otherwise NULL
	WINEVENTPROC,  # pfnWinEventProc: Pointer to the event hook function
	DWORD,  # idProcess: The ID of the process from which the hook function receives events
	DWORD,  # idThread: The ID of the thread from which the hook function receives events
	DWORD,  # dwFlags: Specifies the location of the hook function and of the events to be skipped
)

UnhookWinEvent = dll.UnhookWinEvent
"""
Removes an event hook function created by a previous call to SetWinEventHook.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-unhookwinevent
"""
UnhookWinEvent.restype = BOOL
UnhookWinEvent.argtypes = (
	HWINEVENTHOOK,  # hWinEventHook: Handle to the event to unhook
)

NotifyWinEvent = dll.NotifyWinEvent
"""
Signals the system that a predefined event occurred.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-notifywinevent
"""
NotifyWinEvent.restype = None
NotifyWinEvent.argtypes = (
	DWORD,  # event: The event that occurred
	HWND,  # hwnd: Handle to the window that contains the object that generated the event
	LONG,  # idObject: The object that generated the event
	LONG,  # idChild: Whether the event was generated by an object or one of its children
)

CreateWindowEx = dll.CreateWindowExW
"""
Creates an overlapped, pop-up, or child window with an extended window style.
.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-createwindowexw
"""
CreateWindowEx.argtypes = (
	DWORD,  # dwExStyle
	LPCWSTR,  # lpClassName
	LPCWSTR,  # lpWindowName
	DWORD,  # dwStyle
	c_int,  # x
	c_int,  # y
	c_int,  # nWidth
	c_int,  # nHeight
	HWND,  # hWndParent
	HMENU,  # hMenu
	HINSTANCE,  # hInstance
	c_void_p,  # lpParam
)
CreateWindowEx.restype = HWND

RegisterClassEx = dll.RegisterClassExW
"""
Registers a window class for subsequent use in calls to the CreateWindow or CreateWindowEx function.
.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-registerclassexw
"""
RegisterClassEx.argtypes = (
	POINTER(WNDCLASSEXW),  # lpWndClass
)
RegisterClassEx.restype = ATOM

UnregisterClass = dll.UnregisterClassW
"""
Unregisters a window class, freeing the memory used by the class and removing it from the system.
.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-unregisterclassw
"""
UnregisterClass.argtypes = (
	LPCWSTR,  # lpClassName
	HINSTANCE,  # hInstance
)
UnregisterClass.restype = BOOL

BeginPaint = dll.BeginPaint
"""
Begins painting in the specified window by filling a PAINTSTRUCT structure with information about the painting.
.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-beginpaint
"""
BeginPaint.argtypes = (
	HWND,  # hWnd
	POINTER(PAINTSTRUCT),  # lpPaint
)
BeginPaint.restype = HDC

EndPaint = dll.EndPaint
"""
Ends painting in the specified window by releasing the device context (DC) and invalidating the PAINTSTRUCT structure.
.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-endpaint
"""
EndPaint.argtypes = (
	HWND,  # hWnd
	POINTER(PAINTSTRUCT),  # lpPaint
)
EndPaint.restype = BOOL

OpenClipboard = dll.OpenClipboard
"""
Opens the clipboard for examination and prevents other applications from modifying the clipboard content until the clipboard is closed.
.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-openclipboard
"""
OpenClipboard.argtypes = (
	HWND,  # hWndNewOwner
)
OpenClipboard.restype = BOOL

CloseClipboard = dll.CloseClipboard
"""
Closes the clipboard and releases ownership of the clipboard to other applications.
.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-closeclipboard
"""
CloseClipboard.argtypes = ()
CloseClipboard.restype = BOOL

GetClipboardData = dll.GetClipboardData
"""
Retrieves data from the clipboard in a specified format.
.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getclipboarddata
"""
GetClipboardData.argtypes = (
	UINT,  # uFormat
)
GetClipboardData.restype = HANDLE

SetClipboardData = dll.SetClipboardData
"""
Places data on the clipboard in a specified format.
.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setclipboarddata
"""
SetClipboardData.argtypes = (
	UINT,  # uFormat
	HANDLE,  # hMem
)
SetClipboardData.restype = HANDLE

WNDENUMPROC = WINFUNCTYPE(BOOL, HWND, LPARAM)
"""
An application-defined callback function used with the EnumWindows or EnumDesktopWindows function.
It receives top-level window handles.
"""

EnumWindows = dll.EnumWindows
"""
Enumerates all top-level windows on the screen by passing the handle to each window,
in turn, to an application-defined callback function.
EnumWindows continues until the last top-level window is enumerated or the callback function returns FALSE.
.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-enumwindows
"""
EnumWindows.argtypes = (
	WNDENUMPROC,  # lpEnumFunc
	LPARAM,  # lParam
)
EnumWindows.restype = BOOL

GetSystemMetrics = dll.GetSystemMetrics
"""
Retrieves the specified system metric or system configuration setting.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmetrics
"""
GetSystemMetrics.restype = c_int
GetSystemMetrics.argTypes = (
	c_int,  # nIndex: The system metric or configuration setting to be retrieved
)

ChangeWindowMessageFilter = dll.ChangeWindowMessageFilter
"""
Adds or removes a message from the User Interface Privilege Isolation (UIPI) message filter.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-changewindowmessagefilter
"""
ChangeWindowMessageFilter.restype = BOOL
ChangeWindowMessageFilter.argTypes = (
	UINT,  # message: The message to add to or remove from the filter
	DWORD,  # dwFlag: The action to be performed
)

GetKeyState = dll.GetKeyState
"""
Retrieves the status (up, down, or toggled) of the specified virtual key.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getkeystate
"""
GetKeyState.restype = SHORT
GetKeyState.argtypes = (
	c_int,  # nVirtKey: A virtual key
)

SystemParametersInfoW = dll.SystemParametersInfoW
"""
Retrieves or sets the value of one of the system-wide parameters.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-systemparametersinfow
"""
SystemParametersInfoW.restype = BOOL
SystemParametersInfoW.argtypes = (
	UINT,  # uiAction: The system-wide parameter to be retrieved or set
	UINT,  # uiParam: A parameter whose usage and format depends on the system parameter being queried or set
	c_void_p,  # pvParam: A parameter whose usage and format depends on the system parameter being queried or set
	UINT,  # fWinIni: If setting a system parameter, Whether to update the user profile, and if so, whether to  broadcast the change
)

WaitMessage = dll.WaitMessage
"""
Blocks thread execution until the thread needs to process a new message.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-waitmessage
"""
WaitMessage.restype = BOOL
WaitMessage.argtypes = ()

TranslateMessage = dll.TranslateMessage
"""
Translates virtual-key messages into character messages.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-translatemessage
"""
TranslateMessage.restype = BOOL
TranslateMessage.argtypes = (
	PMSG,  # lpMsg: A message retrieved from the calling thread's message queue
)

DispatchMessage = dll.DispatchMessageW
"""
Dispatches a message to a window procedure.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-dispatchmessagew
"""
DispatchMessage.restype = LRESULT
DispatchMessage.argtypes = (
	PMSG,  # lpMsg
)

PeekMessage = dll.PeekMessageW
"""
Dispatches incoming nonqueued messages, checks the thread message queue for a posted message, and retrieves the message (if any exist).

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-peekmessagew
"""
PeekMessage.restype = BOOL
PeekMessage.argtypes = (
	LPMSG,  # lpMsg: Pointer to an MSG structure that receives message information
	HWND,  # hWnd: Handle to the window whose messages are to be retrieved
	UINT,  # wMsgFilterMin: The value of the first message in the range of messages to be examined
	UINT,  # wMsgFilterMax: The value of the last message in the range of messages to be examined
	UINT,  # wRemoveMsg: Specifies how messages are to be handled
)

SendMessage = dll.SendMessageW
"""
Sends the specified message to a window or windows and does not return until the message has been processed.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendmessagew
"""
SendMessage.restype = LRESULT
SendMessage.argtypes = (
	HWND,  # hWnd: Handle to the window whose window procedure will receive the message
	UINT,  # Msg: The message to be sent
	WPARAM,  # wParam: Additional message-specific information
	LPARAM,  # lParam: Additional message-specific information
)

PostMessage = dll.PostMessageW
"""
Places a message in the message queue associated with the thread that created the specified window and returns without waiting for the thread to process the message.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-postmessagew
"""
PostMessage.restype = BOOL
PostMessage.argtypes = (
	HWND,  # hWnd: Handle to the window whose window procedure is to receive the message
	UINT,  # Msg: The message to be posted
	WPARAM,  # wParam: Additional message-specific information
	LPARAM,  # lParam: Additional message-specific information
)

GetAsyncKeyState = dll.GetAsyncKeyState
"""
Determines whether a key is up or down at the time the function is called.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getasynckeystate
"""
GetAsyncKeyState.restype = SHORT
GetAsyncKeyState.argtypes = (
	c_int,  # vKey: The virtual-key code
)

IsWindow = dll.IsWindow
"""
Determines whether the specified window handle identifies an existing window.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-iswindow
"""
IsWindow.restype = BOOL
IsWindow.argtypes = (
	HWND,  # hWnd: A handle to the window to be tested
)

IsChild = dll.IsChild
"""
Determines whether a window is a child or descendant window of a specified parent window.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-ischild
"""
IsChild.restype = BOOL
IsChild.argtypes = (
	HWND,  # hWndParent: Handle to the parent window
	HWND,  # hWnd: Handle to the window to be tested
)

GetForegroundWindow = dll.GetForegroundWindow
"""
Retrieves a handle to the foreground window (the window with which the user is currently working)

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getforegroundwindow
"""
GetForegroundWindow.restype = HWND
GetForegroundWindow.argtypes = ()

SetForegroundWindow = dll.SetForegroundWindow
"""
Brings the thread that created the specified window into the foreground and activates the window.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setforegroundwindow
"""
SetForegroundWindow.restype = BOOL
SetForegroundWindow.argtypes = (
	HWND,  # hWnd: Handle to the window that should be activated and brought to the foreground.
)

SetFocus = dll.SetFocus
"""
Sets the keyboard focus to the specified window.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setfocus
"""
SetFocus.restype = HWND
SetFocus.argtypes = (
	HWND,  # hWnd: Handle to the window that will receive the keyboard input
)

GetDesktopWindow = dll.GetDesktopWindow
"""
Retrieves a handle to the desktop window.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getdesktopwindow
"""
GetDesktopWindow.restype = HWND
GetDesktopWindow.argtypes = ()

GetWindowLong = dll.GetWindowLongW
"""
Retrieves information about the specified window.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowlongw
"""
GetWindowLong.restype = LONG
GetWindowLong.argtypes = (
	HWND,  # hWnd: Handle to the window and, indirectly, the class to which the window belongs
	c_int,  # nIndex: Zero-based offset to the value to be retrieved
)

TIMERPROC = WINFUNCTYPE(None, HWND, UINT, UINT_PTR, DWORD)
"""
An application-defined callback function that processes WM_TIMER messages.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nc-winuser-timerproc
"""

SetTimer = dll.SetTimer
"""
Creates a timer with the specified time-out value.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-settimer
"""
SetTimer.restype = UINT_PTR
SetTimer.argtypes = (
	HWND,  # hWnd: handle to the window to be associated with the timer
	UINT_PTR,  # nIDEvent: A nonzero timer identifier
	UINT,  # uElapse: The time-out value, in milliseconds
	TIMERPROC,  # lpTimerFunc: Pointer to the function to be notified when the time-out value elapses
)

KillTimer = dll.KillTimer
"""
Destroys the specified timer.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-killtimer
"""
KillTimer.restype = BOOL
KillTimer.argTypes = (
	HWND,  # hWnd: Handle to the window associated with the specified timer
	UINT_PTR,  # uIDEvent: The timer to be destroyed
)


class MOUSEINPUT(Structure):
	"""
	Contains information about a simulated mouse event.

	.. seealso::
		https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-mouseinput
	"""

	_fields_ = (
		("dx", LONG),
		("dy", LONG),
		("mouseData", DWORD),
		("dwFlags", DWORD),
		("time", DWORD),
		("dwExtraInfo", ULONG_PTR),
	)


class KEYBDINPUT(Structure):
	"""
	Contains information about a simulated keyboard event.

	.. seealso::
		https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-keybdinput
	"""

	_fields_ = (
		("wVk", WORD),
		("wScan", WORD),
		("dwFlags", DWORD),
		("time", DWORD),
		("dwExtraInfo", ULONG_PTR),
	)


class HARDWAREINPUT(Structure):
	"""
	Contains information about a simulated message generated by an input device other than a keyboard or mouse.

	.. seealso::
		https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-hardwareinput
	"""

	_fields_ = (
		("uMsg", DWORD),
		("wParamL", WORD),
		("wParamH", WORD),
	)


class _INPUT_I(Union):
	"""
	Type of `Input.DUMMYUNIONNAME`.
	"""

	_fields_ = (
		("mi", MOUSEINPUT),
		("ki", KEYBDINPUT),
		("hi", HARDWAREINPUT),
	)


class INPUT(Structure):
	"""
	Used by SendInput to store information for synthesizing input events such as keystrokes, mouse movement, and mouse clicks.

	.. seealso::
		https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-input
	"""

	_fields_ = (
		("type", DWORD),
		("ii", _INPUT_I),
	)


LPINPUT = POINTER(INPUT)

SendInput = dll.SendInput
"""
Synthesizes keystrokes, mouse motions, and button clicks.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-sendinput
"""
SendInput.restype = UINT
SendInput.argtypes = (
	UINT,  # cInputs: The number of structures in the pInputs array
	LPINPUT,  # pInputs: Array of events to be inserted into the keyboard or mouse input stream
	c_int,  # cbSize: The size, in bytes, of an INPUT structure
)

keybd_event = dll.keybd_event
"""
Synthesizes a keystroke.

.. note::
	This function has been superseded. Use ``SendInput`` instead.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-keybd_event
"""
keybd_event.restype = None
keybd_event.argtypes = (
	BYTE,  # bVk: A virtual-key code
	BYTE,  # bScan: Hardware scan code for the key
	DWORD,  # dwFlags: Controls various aspects of function operation
	ULONG_PTR,  # dwExtraInfo: An additional value associated with the key stroke
)

mouse_event = dll.mouse_event
"""
Synthesizes mouse motion and button clicks.

.. note::
	This function has been superseded. Use `SendInput` instead.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-mouse_event
"""
mouse_event.restype = None
mouse_event.argtypes = (
	DWORD,  # dwFlags: Controls various aspects of mouse motion and button clicking
	DWORD,  # dx: The absolute position or amount of motion along the x-axis
	DWORD,  # dy: The absolute position or amount of motion along the y-axis
	DWORD,  # dwData: Specifics of the event
	ULONG_PTR,  # dwExtraInfo: An additional value associated with the mouse event
)

VkKeyScanEx = dll.VkKeyScanExW
"""
Translates a character to the corresponding virtual-key code and shift state.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-vkkeyscanexw
"""
VkKeyScanEx.restype = SHORT
VkKeyScanEx.argtypes = (
	WCHAR,  # ch: The character to be translated into a virtual-key code
	HKL,  # dwhkl: Input locale identifier used to translate the character
)

GetKeyNameText = dll.GetKeyNameTextW
"""
Retrieves a string that represents the name of a key.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-GetKeyNameTextW
"""
GetKeyNameText.restype = int
GetKeyNameText.argtypes = (
	LONG,  # lParam: The second parameter of the keyboard message (such as WM_KEYDOWN) to be processed
	LPWSTR,  # lpString: The buffer that will receive the key name
	c_int,  # cchSize: The maximum length, in characters, of the key name, including the terminating null character
)

GetKeyboardLayout = dll.GetKeyboardLayout
"""
Retrieves the active input locale identifier (formerly called the keyboard layout).

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-GetKeyboardLayout
"""
GetKeyboardLayout.restype = HKL
GetKeyboardLayout.argtypes = (
	DWORD,  # idThread: The identifier of the thread to query, or 0 for the current thread
)

GetPhysicalCursorPos = dll.GetPhysicalCursorPos
"""
Retrieves the position of the cursor in physical coordinates.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getphysicalcursorpos
"""
GetPhysicalCursorPos.restype = BOOL
GetPhysicalCursorPos.argtypes = (
	LPPOINT,  # lpPoint: The position of the cursor, in physical coordinates
)

SetPhysicalCursorPos = dll.SetPhysicalCursorPos
"""
Sets the position of the cursor in physical coordinates.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-SetPhysicalCursorPos
"""
SetPhysicalCursorPos.restype = BOOL
SetPhysicalCursorPos.argtypes = (
	c_int,  # X: The new x-coordinate of the cursor, in physical coordinates
	c_int,  # Y: The new y-coordinate of the cursor, in physical coordinates
)

GetWindowThreadProcessId = dll.GetWindowThreadProcessId
"""
Retrieves the identifier of the thread that created the specified window and, optionally, the identifier of the process that created the window.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindowthreadprocessid
"""
GetWindowThreadProcessId.restype = DWORD
GetWindowThreadProcessId.argtypes = (
	HWND,  # hWnd: Handle to the window
	LPDWORD,  # lpdwProcessId: Optional pointer to a variable that receives the process identifier
)

GetClassName = dll.GetClassNameW
"""
Retrieves the name of the class to which the specified window belongs.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getclassnamew
"""
GetClassName.restype = c_int
GetClassName.argtypes = (
	HWND,  # hWnd: Handle to the window and, indirectly, the class to which the window belongs
	LPWSTR,  # lpClassName: The class name string
	c_int,  # nMaxCount: Length of the lpClassName buffer, in characters
)

GetAncestor = dll.GetAncestor
"""
Retrieves the handle to the ancestor of the specified window.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getancestor
"""
GetAncestor.restype = HWND
GetAncestor.argtypes = (
	HWND,  # hwnd: Handle to the window whose ancestor is to be retrieved
	UINT,  # gaFlags: The ancestor to be retrieved
)

GetCaretPos = dll.GetCaretPos
"""
Copies the caret's position to the specified POINT structure.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getcaretpos
"""
GetCaretPos.restype = BOOL
GetCaretPos.argtypes = (
	LPPOINT,  # lpPoint: pointer to the POINT structure that is to receive the client coordinates of the caret
)


GetTopWindow = dll.GetTopWindow
"""
retrieves a handle to the parent window's  top most child window  in the Z order.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-gettopwindow
"""
GetTopWindow.restype = HWND
GetTopWindow.argtypes = (
	HWND,  # hWnd: Handle to the parent window whose child windows are to be examined
)

InternalGetWindowText = dll.InternalGetWindowText
"""
Copies the text of the specified window's title bar (if it has one) into a buffer.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-internalgetwindowtext
"""
InternalGetWindowText.restype = c_int
InternalGetWindowText.argtypes = (
	HWND,  # hWnd : handle to the window or control containing the text
	LPWSTR,  # pString: The buffer that is to receive the text
	c_int,  # cchMaxCount: Maximum number of characters to be copied to the buffer, including the null character
)

GetWindow = dll.GetWindow
"""
Retrieves a handle to a window that has the specified relationship to the specified window.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getwindow
"""
GetWindow.restype = HWND
GetWindow.argtypes = (
	HWND,  # hWnd: Handle to a window
	UINT,  # uCmd: The relationship between the specified window and the window to be retrieved
)

IsWindowVisible = dll.IsWindowVisible
"""
Determines the visibility state of the specified window.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-iswindowvisible
"""
IsWindowVisible.restype = BOOL
IsWindowVisible.argtypes = (
	HWND,  # hWnd: Handle to the window to be tested
)

IsWindowEnabled = dll.IsWindowEnabled
"""
Determines whether the specified window is enabled for mouse and keyboard input.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-iswindowenabled
"""
IsWindowEnabled.restype = BOOL
IsWindowEnabled.argtypes = (
	HWND,  # hWnd: Handle to the window to be tested
)


class GUITHREADINFO(Structure):
	"""
	Contains information about a GUI thread.

	.. seealso::
		https://learn.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-guithreadinfo
	"""

	_fields_ = (
		("cbSize", DWORD),
		("flags", DWORD),
		("hwndActive", HWND),
		("hwndFocus", HWND),
		("hwndCapture", HWND),
		("hwndMenuOwner", HWND),
		("hwndMoveSize", HWND),
		("hwndCaret", HWND),
		("rcCaret", RECT),
	)


PGUITHREADINFO = POINTER(GUITHREADINFO)


GetGUIThreadInfo = dll.GetGUIThreadInfo
"""
Retrieves information about the active window or a specified GUI thread.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getguithreadinfo
"""
GetGUIThreadInfo.restype = BOOL
GetGUIThreadInfo.argtypes = (
	DWORD,  # idThread: The identifier of the thread for which information is to be retrieved
	PGUITHREADINFO,  # pgui: pointer to a GUITHREADINFO structure that receives information describing the thread
)

SetWindowLong = dll.SetWindowLongW
"""
Changes an attribute of the specified window.

.. note::
	This function has been superseded by the ``SetWindowLongPtr`` function.
	To write code that is compatible with both 32-bit and 64-bit versions of Windows,
	use the ``SetWindowLongPtr`` function.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowlongw
"""
SetWindowLong.restype = LONG
SetWindowLong.argtypes = (
	HWND,  # hWnd: Handle to the window and, indirectly, the class to which the window belongs.
	c_int,  # nIndex: Zero-based offset to the value to be set
	LONG,  # dwNewLong: The replacement value
)


SetLayeredWindowAttributes = dll.SetLayeredWindowAttributes
"""
Sets the opacity and transparency color key of a layered window.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setlayeredwindowattributes
"""
SetLayeredWindowAttributes.restype = BOOL
SetLayeredWindowAttributes.argtypes = (
	HWND,  # hwnd: Handle to the layered window
	COLORREF,  # crKey: the transparency color key to be used when composing the layered window
	BYTE,  # bAlpha: Alpha value used to describe the opacity of the layered window
	DWORD,  # dwFlags: An action to be taken
)


RedrawWindow = dll.RedrawWindow
"""
Updates the specified rectangle or region in a window's client area.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-redrawwindow
"""
RedrawWindow.restype = BOOL
RedrawWindow.argtypes = (
	HWND,  # hWnd: Handle to the window to be redrawn
	PRECT,  # lprcUpdate: The coordinates, in device units, of the update rectangle
	HRGN,  # hrgnUpdate: Handle to the update region
	UINT,  # flags: One or more redraw flags
)


FindWindow = dll.FindWindowW
"""
Retrieves a handle to the top-level window whose class name and window name match the specified strings.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-findwindoww
"""
FindWindow.restype = HWND
FindWindow.argtypes = (
	LPCWSTR,  # lpClassName: The class name or a class atom
	LPCWSTR,  # lpWindowName: The window name (title)
)

MessageBox = dll.MessageBoxW
"""
Displays a modal dialog box.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-messageboxw
"""
MessageBox.restype = c_int
MessageBox.argtypes = (
	HWND,  # hWnd: Optional handle to the owner window of the message box
	LPCWSTR,  # lpText: The message to be displayed
	LPCWSTR,  # lpCaption: The dialog box title
	UINT,  # uType: The contents and behavior of the dialog box
)

ScreenToClient = dll.ScreenToClient
"""
Converts the screen coordinates of a specified point on the screen to client-area coordinates.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-screentoclient
"""
ScreenToClient.restype = BOOL
ScreenToClient.argtypes = (
	HWND,  # hWnd: handle to the window whose client area will be used for the conversion
	LPPOINT,  # lpPoint: the screen coordinates to be converted
)

ClientToScreen = dll.ClientToScreen
"""
converts the client-area coordinates of a specified point to screen coordinates.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-clienttoscreen
"""
ClientToScreen.restype = BOOL
ClientToScreen.argtypes = (
	HWND,  # hWnd: Handle to the window whose client area is used for the conversion
	LPPOINT,  # lpPoint: The client coordinates to be converted
)

WindowFromPoint = dll.WindowFromPoint
"""
Retrieves a handle to the window that contains the specified point.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-windowfrompoint
"""
WindowFromPoint.restype = HWND
WindowFromPoint.argtypes = (
	POINT,  # Point: The point to be checked
)

AttachThreadInput = dll.AttachThreadInput
"""
Attaches or detaches the input processing mechanism of one thread to that of another thread.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-AttachThreadInput
"""
AttachThreadInput.restype = BOOL
AttachThreadInput.argtypes = (
	DWORD,  # idAttach: The identifier of the thread to be attached to another thread
	DWORD,  # idAttachTo: The identifier of the thread to which idAttach will be attached
	BOOL,  # fAttach: If TRUE, the threads are attached; otherwise, they are detached
)

MapVirtualKeyEx = dll.MapVirtualKeyExW
"""
Translates a virtual-key code or scan code  into a scan code, character value or virtual-key code.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-MapVirtualKeyExW
"""
MapVirtualKeyEx.restype = UINT
MapVirtualKeyEx.argtypes = (
	UINT,  # uCode: The virtual key code or scan code for a key
	UINT,  # uMapType: The translation to perform
	HKL,  # dwhkl: Input locale identifier to use for translating the specified code
)

MsgWaitForMultipleObjects = dll.MsgWaitForMultipleObjects
"""
Waits until one or all of the specified objects are in the signaled state or the time-out interval elapses.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-msgwaitformultipleobjects
"""
MsgWaitForMultipleObjects.restype = DWORD
MsgWaitForMultipleObjects.argtypes = (
	DWORD,  # nCount: The number of object handles in the array pointed to by pHandles
	PHANDLE,  # pHandles: An array of object handles
	BOOL,  # fWaitAll: Whether to wait for all handles to be signaled
	DWORD,  # dwMilliseconds: The time-out interval, in milliseconds
	DWORD,  # dwWakeMask: The input types for which an input event object handle will be added to the array of object handles
)

ShowWindow = dll.ShowWindow
"""
Sets the specified window's show state.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-showwindow
"""
ShowWindow.restype = BOOL
ShowWindow.argtypes = (
	HWND,  # hWnd: Handle to the window
	c_int,  # nCmdShow: Controls how the window is to be shown
)

SetWindowPos = dll.SetWindowPos
"""
Changes the size, position, and Z order of a child, pop-up, or top-level window.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-SetWindowPos
"""
SetWindowPos.restype = BOOL
SetWindowPos.argtypes = (
	HWND,  # hWnd:Handle to the window
	HWND,  # hWndInsertAfter: Optional handle to the window to precede the positioned window in the Z order
	c_int,  # X: The new position of the left side of the window, in client coordinates
	c_int,  # Y: The new position of the top of the window, in client coordinates
	c_int,  # cx: The new width of the window, in pixels
	c_int,  # cy: The new height of the window, in pixels
	UINT,  # uFlags: The window sizing and positioning flags
)

UpdateWindow = dll.UpdateWindow
"""
Updates the client area of the specified window by sending a WM_PAINT message to the window if the window's update region is not empty.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-UpdateWindow
"""
UpdateWindow.restype = BOOL
UpdateWindow.argtypes = (
	HWND,  # hWnd: Handle to the window to be updated
)

PostQuitMessage = dll.PostQuitMessage
"""
Indicates to the system that a thread has made a request to terminate.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-postquitmessage
"""
PostQuitMessage.restype = None
PostQuitMessage.argtypes = (
	c_int,  # nExitCode: The application exit code
)

InvalidateRect = dll.InvalidateRect
"""
Adds a rectangle to the specified window's update region.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-invalidaterect
"""
InvalidateRect.restype = BOOL
InvalidateRect.argtypes = (
	HWND,  # hWnd: Handle to the window whose update region has changed
	PRECT,  # lpRect: the client coordinates of the rectangle to be added to the update region
	BOOL,  # bErase: whether to erased the background when processing the update region
)

PostThreadMessage = dll.PostThreadMessageW
"""
Posts a message to the message queue of the specified thread.

.. seealso::
	https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-postthreadmessagew
"""
PostThreadMessage.restype = BOOL
PostThreadMessage.argtypes = (
	DWORD,  # idThread: The identifier of the thread to which the message is to be posted
	UINT,  # Msg: The type of message to be posted
	WPARAM,  # wParam: Additional message-specific information
	LPARAM,  # lParam: Additional message-specific information
)
