name: Check comments for translators

on:
  push:
    branches:
    - master
    - beta
    - rc
    - try-**
    - release-**
    - githubActions # To be removed

  pull_request:
    branches:
    - master
    - beta
    - rc
    - try-**
    - release-**

  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  checkoutRef: ${{ github.event_name == 'pull_request' && github.event.head.sha || '' }}
  if: $GITHUB_EVENT_NAME == 'pull_request'
  pullRequestNumber: ${{ github.event.number }}
  ref: ${{ github.event.pull_request.head.sha }}
jobs:
  checkPot:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - name: Checkout NVDA
      uses: actions/checkout@v4
      with:
        submodules: recursive
        ref: $checkoutRef
    - name: Build NVDA
      uses: ./nvdaBuilder
    - name: Check comments for translators
      run: powershell.exe ci/scripts/tests/translationCheck.ps1
