name: Check comments for translators

on:
  push:
    branches:
    - master
    - beta
    - rc
    - try-**
    - release-**
    - githubActions # To be removed

  pull_request:
    branches:
    - master
    - beta
    - rc
    - try-**
    - release-**

  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  if: $GITHUB_EVENT_NAME == 'pull_request'
  pullRequestNumber: ${{ github.event.number }}
jobs:
  checkPot:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - name: Checkout NVDA
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - name: Checkout pr
      if: ${{ github.event_name == 'pull_request' }}
      run: gh pr checkout $pullRequestNumber
      shell: cmd
    - name: Build NVDA
      uses: ./nvdaBuilder
    - name: Check comments for translators
      run: powershell.exe ci/scripts/tests/translationCheck.ps1
