name: Check comments for translators

on:
  push:
    branches:
    - master
    - beta
    - rc
    - 'try-**'
    - githubActions # To be removed
  tags:
    - release-**

  pull_request:
    branches:
    - master
    - beta
    - rc

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  if: $GITHUB_EVENT_NAME == 'pull_request'
  pullRequestNumber: ${{ github.event.number }}
jobs:
  checkPot:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - name: Checkout NVDA
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build NVDA
      uses: ./nvdaBuilder
      with:
        scons-source: false
    - name: Check comments for translators
      run: powershell.exe ci/scripts/tests/translationCheck.ps1
    - name: Upload artifact
      id: uploadArtifact
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: Check pot results
        path: output//nvda.pot
        overwrite: true
