name: Check licenses

on:
  push:
    branches:
    - master
    - beta
    - rc
    - try-**
    - release-**
    - githubActions # To be removed

  pull_request:
    branches:
    - master
    - beta
    - rc
    - try-**
    - release-**

  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  if: $GITHUB_EVENT_NAME == 'pull_request'
  pullRequestNumber: ${{ github.event.number }}
jobs:
  licenseCheck:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - name: Checkout NVDA
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build NVDA
      uses: ./nvdaBuilder
      with:
        scons-source: false
    - name: License check
      run: powershell.exe ci/scripts/tests/licenseCheck.ps1
    - name: Upload artifact
      id: uploadArtifact
      if: ${{ always }}
      uses: actions/upload-artifact@v4
      with:
        name: License check results
        path: testOutput/license/licenseCheckResults.md
