name: System tests

on:
  push:
    branches:
    - master
    - beta
    - rc
    - try-**
    - release-**
    - githubActions # To be removed

  pull_request:
    branches:
    - master
    - beta
    - rc
    - try-**
    - release-**

  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  if: $GITHUB_EVENT_NAME == 'pull_request'
  pullRequestNumber: ${{ github.event.number }}
jobs:
  systemTests:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
    - name: Checkout NVDA
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: Build NVDA
      uses: ./nvdaBuilder
    - name: Run scons launcher
      run: scons launcher version=%version% --all-cores
    - name: Install NVDA
      run: powershell.exe ci/scripts/installNVDA.ps1
    - name: Upload NVDA
      id: uploadLauncher
      uses: actions/upload-artifact@v4
      with:
        name: NVDA launcher
        path: output/nvda*.exe
    - name: Run system tests
      run: powershell.exe ci/scripts/tests/systemTests.ps1
    - name: Upload system tests results
      id: uploadSystemTestsResults
      if: ${{ always() }}
      uses: actions/upload-artifact@v4
      with:
        name: System tests results
        path: testOutput/system
    - name: : Add artifact URLs to summary
      run: |
        echo '[- Download NVDA launcher](${{ steps.uploadLauncher.outputs.artifact-url }})' >> $GITHUB_STEP_SUMMARY
        echo '[- Download system tests results](${{ steps.uploadSystemTestsResults.outputs.artifact-url }})' >> $GITHUB_STEP_SUMMARY
